// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducacaoOnline.GestaoAlunos.Data.Migrations
{
    [DbContext(typeof(GestaoAlunosContext))]
    [Migration("20251116194443_ExclusaoCurso")]
    partial class ExclusaoCurso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("EducacaoOnline.GestaoAlunos.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aluno", (string)null);
                });

            modelBuilder.Entity("EducacaoOnline.GestaoAlunos.Domain.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certificado", (string)null);
                });

            modelBuilder.Entity("EducacaoOnline.GestaoAlunos.Domain.HistoricoAprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdMatricula")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoricoAprendizado", (string)null);
                });

            modelBuilder.Entity("EducacaoOnline.GestaoAlunos.Domain.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HistoricoAprendizadoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CertificadoId");

                    b.HasIndex("HistoricoAprendizadoId");

                    b.ToTable("Matricula", (string)null);
                });

            modelBuilder.Entity("EducacaoOnline.GestaoAlunos.Domain.Matricula", b =>
                {
                    b.HasOne("EducacaoOnline.GestaoAlunos.Domain.Aluno", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EducacaoOnline.GestaoAlunos.Domain.Certificado", "Certificado")
                        .WithMany()
                        .HasForeignKey("CertificadoId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EducacaoOnline.GestaoAlunos.Domain.HistoricoAprendizado", "HistoricoAprendizado")
                        .WithMany()
                        .HasForeignKey("HistoricoAprendizadoId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Certificado");

                    b.Navigation("HistoricoAprendizado");
                });

            modelBuilder.Entity("EducacaoOnline.GestaoAlunos.Domain.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
